#!/usr/bin/env bash
# to display the content of the file /etc/passwd
# only to display the username, user id and home directory path for the user

while read -r line
do
	echo "$line" | cut -d: -f1,4,7
done < "/etc/passwd"
