#!/usr/bin/env bash
# information about the shcool file using the if/else statement

file="shcool"
if [ -e "$file" ]
then
    echo "$file file exists"
    if [ -s "$file" ]
	then
		echo "shcool file is not empty"
    else
		echo "shcool file is empty"
    fi
    if [ -f "$file" ]
	then
		echo "shcool is a regular file"
    fi
else
    echo "shcool file does not exist"
fi
